### ISSUE TITLE
调用失败 422 Unprocessable Entity

### ISSUE THREAD

**Issue by kugooer** [JoysKang/fund_pegging#1]
START RequestId: 2fc8736b-a2a4-45cc-b639-4992fe0a4847Report RequestId: 2fc8736b-a2a4-45cc-b639-4992fe0a4847 Duration: 5ms Memory: 1024MB MemUsage: 110.55MBResponse RequestId: 2fc8736b-a2a4-45cc-b639-4992fe0a4847END RequestId: 2fc8736b-a2a4-45cc-b639-4992fe0a4847INFO:     203.0.113.1:52026 - "POST /event-invoke HTTP/1.1" 422 Unprocessable Entity

**Comment by JoysKang** [comment]
生成的镜像本地启动、调用都正常吗？如果正常那应该是部署云函数哪一步出错了

**Comment by kugooer** [comment]
本地启动调用正常。
部署云函数跟您的说明是一致的。
![image](https://user-images.githubusercontent.com/1291557/129832052-f948c19b-89a5-4037-98ef-26a58c62997f.png)

**Comment by kugooer** [comment]
![image](https://user-images.githubusercontent.com/1291557/129832142-1817927f-6d04-4f7a-a4eb-58b86208150e.png)

**Comment by JoysKang** [comment]
这两个配置看下
![image](https://user-images.githubusercontent.com/11786681/129836142-d499ba7a-08fd-417f-8932-1a6412627242.png)

**Comment by JoysKang** [comment]
另 测试时注意测试类型
![image](https://user-images.githubusercontent.com/11786681/129908141-c6a8d104-aab8-4e15-b054-b963741d8f7b.png)

**Comment by kugooer** [comment]
![image](https://user-images.githubusercontent.com/1291557/130169249-d07294fa-9339-44da-8922-4845bbf21555.png)
![image](https://user-images.githubusercontent.com/1291557/130169495-7320b191-d62a-4d3a-80e5-d6177b8bc813.png)
老大，这样是可以了吗？ 麻烦看一下。

**Comment by JoysKang** [comment]
是的 这就是正常的调用  ୧(๑•̀◡•́๑)૭
